// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reconciliation-service/internal/service (interfaces: ReconciliationService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_reconciliation_service.go -package=mocks github.com/reconciliation-service/internal/service ReconciliationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/reconciliation-service/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockReconciliationService is a mock of ReconciliationService interface.
type MockReconciliationService struct {
	ctrl     *gomock.Controller
	recorder *MockReconciliationServiceMockRecorder
	isgomock struct{}
}

// MockReconciliationServiceMockRecorder is the mock recorder for MockReconciliationService.
type MockReconciliationServiceMockRecorder struct {
	mock *MockReconciliationService
}

// NewMockReconciliationService creates a new mock instance.
func NewMockReconciliationService(ctrl *gomock.Controller) *MockReconciliationService {
	mock := &MockReconciliationService{ctrl: ctrl}
	mock.recorder = &MockReconciliationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciliationService) EXPECT() *MockReconciliationServiceMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockReconciliationService) Reconcile(req dto.ReconciliationRequest) (*dto.ReconciliationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", req)
	ret0, _ := ret[0].(*dto.ReconciliationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockReconciliationServiceMockRecorder) Reconcile(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockReconciliationService)(nil).Reconcile), req)
}
