// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reconciliation-service/internal/repository (interfaces: TransactionRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_transaction_repository.go -package=mocks github.com/reconciliation-service/internal/repository TransactionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"
	time "time"

	model "github.com/reconciliation-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// GetBankStatements mocks base method.
func (m *MockTransactionRepository) GetBankStatements(filePath, bankSource string, startDate, endDate time.Time) ([]model.BankStatement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankStatements", filePath, bankSource, startDate, endDate)
	ret0, _ := ret[0].([]model.BankStatement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankStatements indicates an expected call of GetBankStatements.
func (mr *MockTransactionRepositoryMockRecorder) GetBankStatements(filePath, bankSource, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankStatements", reflect.TypeOf((*MockTransactionRepository)(nil).GetBankStatements), filePath, bankSource, startDate, endDate)
}

// GetSystemTransactions mocks base method.
func (m *MockTransactionRepository) GetSystemTransactions(filePath string, startDate, endDate time.Time) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemTransactions", filePath, startDate, endDate)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemTransactions indicates an expected call of GetSystemTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetSystemTransactions(filePath, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetSystemTransactions), filePath, startDate, endDate)
}

// ParseBankStatements mocks base method.
func (m *MockTransactionRepository) ParseBankStatements(r io.Reader, bankSource string, startDate, endDate time.Time) ([]model.BankStatement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBankStatements", r, bankSource, startDate, endDate)
	ret0, _ := ret[0].([]model.BankStatement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseBankStatements indicates an expected call of ParseBankStatements.
func (mr *MockTransactionRepositoryMockRecorder) ParseBankStatements(r, bankSource, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBankStatements", reflect.TypeOf((*MockTransactionRepository)(nil).ParseBankStatements), r, bankSource, startDate, endDate)
}

// ParseSystemTransactions mocks base method.
func (m *MockTransactionRepository) ParseSystemTransactions(r io.Reader, startDate, endDate time.Time) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseSystemTransactions", r, startDate, endDate)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSystemTransactions indicates an expected call of ParseSystemTransactions.
func (mr *MockTransactionRepositoryMockRecorder) ParseSystemTransactions(r, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSystemTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).ParseSystemTransactions), r, startDate, endDate)
}
